[versions]
kotlin = "1.8.10"
inmo-tgbotapi = "7.0.1"
koin = "3.3.3"
kotlinx-serialization = "1.5.0"
exposed = "0.41.1"
xerial-sqlite = "3.41.0.0"

[libraries]
inmo-tgbotapi = { module = "dev.inmo:tgbotapi", version.ref = "inmo-tgbotapi" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
xerial-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "xerial-sqlite" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
exposed = ["exposed-core", "exposed-jdbc"]
